<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Azure Maps Azure.Maps.Weather</Description>
    <AssemblyTitle>Azure Maps Azure.Maps.Weather</AssemblyTitle>
    <Version>1.0.0-beta.1</Version>
    <PackageTags>Azure;Azure Maps;Maps Azure.Maps.Weather</PackageTags>
    <TargetFrameworks>$(RequiredTargetFrameworks)</TargetFrameworks>
    <NoWarn>$(NoWarn);AZC0012</NoWarn>
    <AotCompatOptOut>true</AotCompatOptOut>
    <IncludeOperationsSharedSource>true</IncludeOperationsSharedSource>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" />
  </ItemGroup>

  <!-- Shared source from Azure.Core -->
  <ItemGroup>
    <Compile Include="$(AzureCoreSharedSources)AzureResourceProviderNamespaceAttribute.cs" LinkBase="Shared/Core" />
    <Compile Include="$(AzureCoreSharedSources)ExperimentalAttribute.cs" LinkBase="Shared/Core" />
    <Compile Include="$(AzureCoreSharedSources)AzureKeyCredentialPolicy.cs" LinkBase="Shared/Core" />
  </ItemGroup>

</Project>
